import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en: {
        searchPlaceholder: 'Search',
        submitButton: 'Submit',
        logout: 'Logout',
        login: 'Login',
        employer: 'Employer',
        registration: 'Registration',
        authorization: 'Authorization',
        name: "Enter name",
        enterlogin: "Enter login",
        password: "Enter password",
        email: "Enter email",
        role: "Choose role",
        searcher: "Searcher",
        noakk: "No account?",
        haveakk: "Have account?",
        resume: "Resume name",
        enterresume: "Enter resume name",
        phone: "Phone",
        enterphone: "Enter phone",
        city: "City",
        enterCity: "Enter city",
        speciality: "Speciality",
        enterspeciality: "Enter speciality",
        resumetext: "Resume text",
        enterresumetext: "Enter resume text",
        createresume: "Create resume",
        saveresume: "Save resume",
        rating: "Rating",
        save: "Buy",
        saved: "Added",
        createjob: "Create job",
        savejob: "Save job",
        aprove: "Aprove",
        denied: "Denied",
        jobname: "Job name",
        company: "Company name",
        salary: "Salary",
        jobtext: "Job text",
        createGuitar: "Create Guitar",
        enterName: "Enter name",
        brand: "Brand",
        enterBrand: "Enter brand",
        description: "Description",
        enterDescription: "Enter description",
        price: "Price",
        enterPrice: "Enter price",
        stock: "Stock",
        enterStock: "Enter stock",
        categoryID: "Category ID",
        enterCategoryID: "Enter category ID",
        category:"Category"
    },
    uk: {
        searchPlaceholder: 'Пошук',
        submitButton: 'Підтвердити',
        logout: 'Вийти',
        login: 'Увійти',
        employer: 'Роботодавець',
        registration: 'Реєстрація',
        authorization: 'Авторизуватись',
        name: "Введіть Ім'я",
        enterlogin: "Введіть логін",
        password: "Введіть пароль",
        email: "Введіть пошту",
        role: "Оберіть роль",
        searcher: "Шукач",
        noakk: "Нема аккаунту?",
        haveakk: "Є аккаунт",
        resume: "Назва резюме",
        enterresume: "Введіть назву рузюме",
        phone: "Телефон",
        enterphone: "Введіть номер телефона",
        city: "Місто",
        enterCity: "Введіть місто",
        speciality: "Спеціальність",
        enterspeciality: "Введіть спеціальність",
        resumetext: "Текст резюме",
        enterresumetext: "Введіть текст резюме",
        createresume: "Створити резюме",
        saveresume: "Збережені резюме",
        rating: "Рейтинг",
        save: "Купити",
        saved: "Додано",
        createjob: "Створити вакансію",
        savejob: "Зберегти вакансію",
        aprove: "Підтвердити",
        denied: "Відмовити",
        jobname: "Назва вакансії",
        company: "Назва компанії",
        salary: "Зарплатня",
        jobtext: "Опис вакансії",
        createGuitar: "Створити Гітару",
        enterName: "Введіть назву",
        brand: "Бренд",
        enterBrand: "Введіть бренд",
        description: "Опис",
        enterDescription: "Введіть опис",
        price: "Ціна",
        enterPrice: "Введіть ціну",
        stock: "Кількість на складі",
        enterStock: "Введіть кількість на складі",
        categoryID: "ID Категорії",
        enterCategoryID: "Введіть ID категорії",
        category:"Категорія"
    },
});

export default strings;
